name: Release validation
on:
  issues:
    types: [opened]

env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: action/checkout@v2
    - name: Get issue body
      run: |
        BODY=${{ github.event.issue.body }}
        echo "$BODY"
