name: Release validation
on:
  issue_comment:
    types: [created, edited]

env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  macos-napi:
    name: Validate NAPI macos - Node ${{matrix.nodejs}} - ${{matrix.arch}}
    runs-on: macos-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
        nodejs:
          - 18
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.nodejs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Pull artifacts
        run: |
          curl -L -O ${{ github.event.issue.body }}/napi-darwin-unknown-x64.tar.gz
          tar -xvzf napi-darwin-unknown-x64.tar.gz

      - name: Test loading Node binaries lib
        run: |
          node load_test.js
  linux-napi:
    name: Build NAPI ${{matrix.image}} - Node ${{matrix.nodejs}} - ${{matrix.cpu.platform}}
    runs-on: ubuntu-22.04
    timeout-minutes: 3000

    strategy:
      fail-fast: false
      matrix:
        image:
          - { name: "linux_glibc", artifact: "linux-glibc" }
          - { name: "linux_musl", artifact: "linux-musl" }
        nodejs:
          - 18
        cpu:
          - { arch: "x86_64", platform: "x86_64", artifact: "x64" }
          - { arch: "aarch64", platform: "arm64", artifact: "arm64" }

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Linux Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./pkg/${{matrix.image.name}}
          load: true
          tags: build:latest
          platforms: linux/${{matrix.cpu.arch}}
          build-args: |
            PLATFORM=${{matrix.cpu.platform}}
            ARCH=${{matrix.cpu.arch}}
            NODE_VERSION=${{matrix.nodejs}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pull artifacts
        run: |
          curl -L -O ${{ github.event.issue.body }}/napi-${{matrix.image.artifact}}-x64.tar.gz
          tar -xvzf *.tar.gz

      - name: Build and Test NAPI file
        run: |
          docker run -i -v $PWD:/src build:latest \
              node /src/load_test.js

